### ISSUE TITLE
how to train with custom dataset?

### ISSUE THREAD

**Issue by marziyemahmoudifar** [Kwentar/Color2Embed_pytorch#2]
Hi,
I want to train this code with my own dataset.
How can I give my dataset as input to the network?

**Comment by Kwentar** [comment]
Hi, see 2nd paragraph in Train section in Readme:
> Unpack it and made train list: each line of simple text file should be path to file, e.g. n09428293/n09428293_23938.JPEG or full path, set up path to this text file in config.IMAGENET_LIST. If you have full path in list, set config.IMAGENET_PREFIX = '' or to prefix if you extract it, btw os.path.join(config.IMAGENET_PREFIX, <image_list_item>) should be valid path to image

i.e. you have your own dataset with images `images/image1.png`, `images/image2.png`, so your IMAGENET_LIST (it is just txt file) will be like:
```
images/image1.png
images/image2.png
...
images/imageN.png
```
And you can train with your images, just change train list

**Comment by marziyemahmoudifar** [comment]
Can I use pre-trained model as initial weights to continue training with my
own dataset?

**Comment by Kwentar** [comment]
I guess yes, why not. But I didnt do anything special for this case

**Comment by marziyemahmoudifar** [comment]
Ok, thanks.
