### ISSUE TITLE
KeyError occurred during training

### ISSUE THREAD

**Issue by marziyemahmoudifar** [Kwentar/Color2Embed_pytorch#3]
How do I fix this error?
File ~\Downloads\Color2Embed_pytorch-main\color2embed\train.py:48 in train
    world_size = int(os.environ['WORLD_SIZE'])

  File ~\anaconda3\lib\os.py:679 in __getitem__
    raise KeyError(key) from None

KeyError: 'WORLD_SIZE'

**Comment by Kwentar** [comment]
You have to use DDP training from pytorch (training for several GPUs/hosts https://pytorch.org/tutorials/intermediate/ddp_tutorial.html), otherway you should change code. Error means you didnt use it pytorch version is too old.

**Comment by marziyemahmoudifar** [comment]
Do you know how to train the code of this repository(zhaohengyuan1/Color2Embed:
Color2Embed: Fast Exemplar-Based Image Colorization using Color Embeddings.
(github.com) <https://github.com/zhaohengyuan1/Color2Embed>) for my own
dataset?

**Comment by Kwentar** [comment]
Nope, sorry

**Comment by marziyemahmoudifar** [comment]
Thanks

**Comment by marziyemahmoudifar** [comment]
I was able to run the network. I have a question about the train-epochs, at least how many epochs should I take to get good results?
